### ISSUE TITLE
Why would I use this over illuminate/routing or symfony/routing?

### ISSUE THREAD

**Issue by dsge** [gymadarasz/router#1]
Could you write a comparison?

**Comment by gymadarasz** [comment]
Speed! :) I like the laravel and symfony frameworks but the routing the first every single pageload, so my philosophy that routing have to be quick cause it just a simple regex matcher and this syntax easier for me. Anyway, here is a benchmark comparison e.g with FastRouter:
https://github.com/gymadarasz/router-benchmark

**Comment by dsge** [comment]
Illuminate/routing can cache it's routes on every deploy so it doesn't even look at the files containing route definitions until the route cache is cleared.

https://laravel.com/docs/5.1/controllers#route-caching

**Comment by gymadarasz** [comment]
Need for cache if something is too slow. Because your issue is interesting I tried to make a cache for my routing but I didn't get a good result and wondered why so I checked how illuminate/routing working is, so I made a quick measure:

Laravel routing cache for only one route `Route::get('/', 'MyController@myAction1');`
it's cached by `artisan` and I call it 100 times:
("laravel/framework": "5.2.*")

``` php
$start = microtime(true);
// frame cycle for measuring...
for($i=0; $i<100; $i++) {
    // original cache content
    app('router')->setRoutes(
        unserialize(base64_decode('TzozNDoiSWxsdW1pbmF0ZVxSb3V0aW5nXFJvdXRlQ29sbGVjdGlvbiI6NDp7czo5OiIAKgByb3V0ZXMiO2E6Mjp7czozOiJHRVQiO2E6MTp7czoxOiIvIjtPOjI0OiJJbGx1bWluYXRlXFJvdXRpbmdcUm91dGUiOjc6e3M6NjoiACoAdXJpIjtzOjE6Ii8iO3M6MTA6IgAqAG1ldGhvZHMiO2E6Mjp7aTowO3M6MzoiR0VUIjtpOjE7czo0OiJIRUFEIjt9czo5OiIAKgBhY3Rpb24iO2E6NTp7czo0OiJ1c2VzIjtzOjQzOiJBcHBcSHR0cFxDb250cm9sbGVyc1xNeUNvbnRyb2xsZXJAbXlBY3Rpb24xIjtzOjEwOiJjb250cm9sbGVyIjtzOjQzOiJBcHBcSHR0cFxDb250cm9sbGVyc1xNeUNvbnRyb2xsZXJAbXlBY3Rpb24xIjtzOjk6Im5hbWVzcGFjZSI7czoyMDoiQXBwXEh0dHBcQ29udHJvbGxlcnMiO3M6NjoicHJlZml4IjtOO3M6NToid2hlcmUiO2E6MDp7fX1zOjExOiIAKgBkZWZhdWx0cyI7YTowOnt9czo5OiIAKgB3aGVyZXMiO2E6MDp7fXM6MTM6IgAqAHBhcmFtZXRlcnMiO047czoxNzoiACoAcGFyYW1ldGVyTmFtZXMiO047fX1zOjQ6IkhFQUQiO2E6MTp7czoxOiIvIjtyOjQ7fX1zOjEyOiIAKgBhbGxSb3V0ZXMiO2E6MTp7czo1OiJIRUFELyI7cjo0O31zOjExOiIAKgBuYW1lTGlzdCI7YTowOnt9czoxMzoiACoAYWN0aW9uTGlzdCI7YToxOntzOjQzOiJBcHBcSHR0cFxDb250cm9sbGVyc1xNeUNvbnRyb2xsZXJAbXlBY3Rpb24xIjtyOjQ7fX0='))
    );

}
// and show result
var_dump(microtime(true) - $start);
exit;
```

and I measured my router too (the handler controllers were an empty function also both scenario)

``` php

$start = microtime(true);

for($i=0; $i<100; $i++) {
$base = '/router-benchmark';
    $routes = [Router::regex('GET,POST', '/') => 'action_test'];

    try {
        Router::dispatch($routes, $base);
    }
    catch(RouterException $e) {
        MyDefaultControllerClass::indexMethod(null, null);
    }
}
var_dump(microtime(true) - $start);
exit;

```

result:
Laravel routing: (as cached)
`float 0.099999904632568`
My router: (without any cache)
`float 0.032999992370605`

May this is not a full correctly just a quick measuring and not contains all of critical case and a tipically use case results may better for laravel routing but I think the reason why I can not made a good caching that  every data storing and re-parsing is too slow. This router too simple and very quick in native faster than laravel routing as cached.

Note: May in the future if this lib improve and developing to more complex then I will make a cache, actually it is unnecessary.
